name: Docker To Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t fullstackserver:latest .
      - name: Export Docker Image
        run: |
          docker save fullstackserver:latest | gzip > fullstackserver.tar.gz
      - name: Release Docker Image
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            fullstackserver.tar.gz
